FROM golang:1.26.1-alpine

RUN apk add --no-cache gcc musl-dev

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE ${SERVER_PORT}

CMD ["air", "-c", ".air.toml"]
