CREATE TABLE IF NOT EXISTS files (
    id CHAR(36) PRIMARY KEY,
    tenant_id CHAR(36) NOT NULL,
    lead_id CHAR(36) DEFAULT NULL,
    conversation_id CHAR(36) NOT NULL,
    contact_id CHAR(36) NOT NULL,
    message_id CHAR(36) DEFAULT NULL,
    name VARCHAR(255) NOT NULL,
    media_type ENUM('image','document','audio','video','other') NOT NULL DEFAULT 'other',
    mime_type VARCHAR(100) NOT NULL DEFAULT '',
    size_bytes BIGINT NOT NULL DEFAULT 0,
    storage_key VARCHAR(512) NOT NULL,
    direction ENUM('inbound','outbound') NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_files_tenant (tenant_id),
    INDEX idx_files_lead (lead_id),
    INDEX idx_files_conversation (conversation_id),
    INDEX idx_files_tenant_created (tenant_id, created_at),
    INDEX idx_files_tenant_type (tenant_id, media_type),
    CONSTRAINT fk_files_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_files_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id),
    CONSTRAINT fk_files_contact FOREIGN KEY (contact_id) REFERENCES contacts(id),
    CONSTRAINT fk_files_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL,
    CONSTRAINT fk_files_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
