### Login como admin
POST {{base_url}}/login
Content-Type: application/x-www-form-urlencoded

email={{admin_email}}&password={{admin_password}}

> {%
client.global.set("token", response.headers.valueOf("Set-Cookie"));
%}

### Listar tenants
GET {{base_url}}/admin/tenants
Cookie: {{token}}

### Listar tenants com filtro de status
GET {{base_url}}/admin/tenants?status=active
Cookie: {{token}}

### Listar tenants com filtro de tipo
GET {{base_url}}/admin/tenants?type=PJ
Cookie: {{token}}

### Buscar tenants por nome
GET {{base_url}}/admin/tenants?search=escritorio
Cookie: {{token}}

### Criar tenant PJ
POST {{base_url}}/admin/tenants
Content-Type: application/x-www-form-urlencoded
Cookie: {{token}}

name=Escritório Silva & Associados&type=PJ&document=12.345.678/0001-90

> {%
client.global.set("tenant_id", response.headers.valueOf("HX-Redirect").split("/").pop());
%}

### Criar tenant PF
POST {{base_url}}/admin/tenants
Content-Type: application/x-www-form-urlencoded
Cookie: {{token}}

name=Dr. João Pereira&type=PF&document=123.456.789-00

### Ver detalhe do tenant
GET {{base_url}}/admin/tenants/{{tenant_id}}
Cookie: {{token}}

### Editar tenant
PUT {{base_url}}/admin/tenants/{{tenant_id}}
Content-Type: application/x-www-form-urlencoded
Cookie: {{token}}

name=Escritório Silva & Associados LTDA&type=PJ&document=12.345.678/0001-90

### Bloquear tenant
POST {{base_url}}/admin/tenants/{{tenant_id}}/block
Content-Type: application/x-www-form-urlencoded
Cookie: {{token}}

reason=Pagamento em atraso há 30 dias

### Desbloquear tenant
POST {{base_url}}/admin/tenants/{{tenant_id}}/unblock
Content-Type: application/x-www-form-urlencoded
Cookie: {{token}}

reason=Pagamento regularizado

### Ver historico de bloqueio/desbloqueio
GET {{base_url}}/admin/tenants/{{tenant_id}}/block-history
Cookie: {{token}}

### Desativar tenant
DELETE {{base_url}}/admin/tenants/{{tenant_id}}
Cookie: {{token}}

### Tentar acessar sem token (deve retornar 401)
GET {{base_url}}/admin/tenants
